SELECT SYSDATE FROM DUAL;

SELECT RPAD('Soleil', 17, 'bla') FROM DUAL;

SELECT LPAD('M1 GIT EEA', 15, '*.') FROM DUAL;

SELECT SUBSTR('M2 GIT EEA', 6, 3) FROM DUAL;

SELECT SUBSTR('ABCDEFGHIJ', 5, 4) FROM DUAL;

SELECT TO_CHAR (SYSDATE, 'MM-DD-YYYY HH24 : MI:SS') FROM DUAL;

SELECT LENGTH ('WEB WAREHOUSE') FROM DUAL;

SELECT ROUND (17.0958, 1) FROM DUAL;

SELECT ROUND (17.58, 2) FROM DUAL;

SELECT TRUNC (1958.0917, 1) FROM DUAL;

SELECT TRUNC (1958.0917, 2) FROM DUAL;

SELECT ROUND (TO_DATE('2014-02-10'), 'YEAR') FROM DUAL;

SELECT TO_DATE('02-OCT-2014', 'DD-MON-YYYY') FROM DUAL;

ALTER SESSION SET NLS_DATE_LANGUAGE = ' American';

SELECT ROUND(TO_DATE('2014-02-10', 'DD-MON-YYYY'), 'YEAR') FROM DUAL;

ALTER SESSION SET NLS_DATE_LANGUAGE = ' DD-MM-YYYY';
 
SELECT TO_DATE('02-OCT-2014', 'DD-MON-YYYY') FROM DUAL;

SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;

SELECT ADD_MONTHS(SYSDATE, 7) FROM DUAL;

SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, TO_DATE('19-JUN-2004'))) AS AGEBB from DUAL;

SELECT TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')) FROM DUAL;

SELECT SYSTIMESTAMP FROM DUAL;

CREATE SEQUENCE MY_SEQ MINVALUE 1;

SELECT MY_SEQ.NEXTVAL FROM DUAL;

SELECT MY_SEQ.CURRVAL FROM DUAL;

DROP SEQUENCE MY_SEQ;